### ISSUE TITLE
CEP External time

### ISSUE THREAD

**Issue by onthefloorr** [wso2/product-cep#184]
Hi,

Can you take a look at the following page  : 
https://github.com/wso2/siddhi/issues/76 

I really like the project and I would like to use it in my project. My problem is that I can't specify custom time to events ( external time )  .  Unfortunately, there is no option to use custom timestamp for logs except externalTime component.  I wanted to ask is there a way to use custom timestamp for logs, and for each time window ?

**Comment by mohanvive** [comment]
Closing the issue since Siddhi#76 closed.
