### ISSUE TITLE
Can not add event stream definition using source view

### ISSUE THREAD

**Issue by pubudu91** [wso2/product-cep#279]
Event stream definition does not get added when using the source view to define an event stream. Have to switch back to the design view for the 'Add Event Stream' button to work. Using CEP 4.1.

**Comment by dnwick** [comment]
@pubudu91 I just checked the functionality in cep4.1.0 .It works fine. Can you share the stream source you have tried to create ? or any errors in the server log

**Comment by pubudu91** [comment]
@dnwick I just tried adding the streams given in sample no. [https://github.com/wso2/product-cep/tree/master/modules/samples/artifacts/0104/eventstreams](0104). There are no logs in the console. 

However, once I **switch back** to the design view and click the 'Add Event Stream' button, the server logs that the stream definition was successfully deployed.

`[2016-12-07 22:16:50,370]  INFO {org.wso2.carbon.event.stream.core.internal.util.helper.EventStreamConfigurationFileSystemInvoker} -  Stream definition configuration for AvgRoomTempPerMinStream2:1.0.0 saved in the filesystem
[2016-12-07 22:16:50,372]  INFO {org.wso2.carbon.event.stream.core.EventStreamDeployer} -  Stream definition is deployed successfully  : AvgRoomTempPerMinStream2:1.0.0`

**Comment by mohanvive** [comment]
@pubudu91 , Actually you cannot use the stream definition that is deployed in the file system  to create the stream from the source view UI. There is a slight difference in the syntax and this needs to be fixed.. And there is a jira for that in [1].. 

[1] https://wso2.org/jira/browse/CEP-1531

**Comment by pubudu91** [comment]
@mohanvive Ah yes, that is the same issue as the one I experienced I think. It wasn't a major issue though to work with CEP though. Thank you.

**Comment by tishan89** [comment]
closing since we have a jira in[1]

[1] https://wso2.org/jira/browse/CEP-1531
