### ISSUE TITLE
CPU Usage increasing when adding multiple execution plans to read from stream

### ISSUE THREAD

**Issue by Anoukh** [wso2/product-cep#299]
**Description:**
CPU usage increases due to the wait strategy used when creating disruptors

**Suggested Labels:**
bug

**Suggested Assignees:**
@anoukh

**Affected Product Version:**
CEP 4.1.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
Start CEP 4.1.0 server. Add at least 4 execution plans and send events in parallel to each execution plan

**Related Issues:**
N/A

**Comment by mohanvive** [comment]
Fixed in latest product release version.
